services:
  - type: web
    name: tree
    runtime: node
    repo: https://github.com/lastxuan4396/TREE.git
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: WEB_PUSH_CONTACT
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
